### ISSUE TITLE
Dying to findout

### ISSUE THREAD

**Issue by nonexee** [mainframed/DC30_Workshop#1]
Hey m8,
So sorry to be contacting u like this, but i've been trying to find the font used in this 
https://raw.githubusercontent.com/mainframed/DC30_Workshop/main/screenshot.png
for far too long, can you help me out? i need the font used for the "defcon" in the image.

**Comment by mainframed** [comment]
Are you talking about the ASCII art font? It's not a font, I made it myself. If you're talking the extended ascii chars, thats in things like Moebius. If you're talking the whole font, i believe its IBM 3270

**Comment by nonexee** [comment]
Yes i am referring to the font used in the ascii for the "defcon", it looks a lot like https://www.fontspace.com/hirosh-font-f1549 but it am searching for the one that looks more like the one you made. Thanks for replying

**Comment by mainframed** [comment]
It's this font: https://github.com/rbanffy/3270font

**Comment by mainframed** [comment]
Sorry I completely misunderstood. The font is from here: 
![image](https://user-images.githubusercontent.com/1973519/184721547-b98a7460-a003-4cea-aa11-7e31a93cf758.png)

not sure what the exact font used is.

**Comment by mainframed** [comment]
https://creativemarket.com//konstantinestudio/5117203-CITYPOP-Japanese-90s-Retro-Fonts

**Comment by nonexee** [comment]
thats it! thank you so much!
